### ISSUE TITLE
Value is invalid for column other_config

### ISSUE THREAD

**Issue by roytman** [IBM/ovsdb-etcd#109]
13 transact.go:269] create new transaction with request params: &{DBName:OVN_Southbound Operations:[{Op:insert Table:Chassis Row:map[encaps:[named-uuid row2462d882_b70e_43e3_965b_42fd566a98c0] external_ids:[map [[datapath-type ] [iface-types bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan] [is-interconn false] [ovn-bridge-mappings ] [ovn-chassis-mac-mappings ] [ovn-cms-options ] [ovn-enable-lflow-cache true] [ovn-monitor-all true] [port-up-notif true]]] hostname:ovn-control-plane name:3e3edded-a3f2-4cab-b158-da88da75a095 other_config:[map [[datapath-type ] [iface-types bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan] [is-interconn false] [ovn-bridge-mappings ] [ovn-chassis-mac-mappings ] [ovn-cms-options ] [ovn-enable-lflow-cache true] [ovn-monitor-all true] [port-up-notif true]]]] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row3683ef96_0920_4e07_a15a_aa44212c910b UUID:<nil> Comment: Durable:false} {Op:insert Table:Encap Row:map[chassis_name:3e3edded-a3f2-4cab-b158-da88da75a095 ip:172.18.0.2 options:[map [[csum true]]] type:geneve] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row2462d882_b70e_43e3_965b_42fd566a98c0 UUID:<nil> Comment: Durable:false} {Op:insert Table:Chassis_Private Row:map[chassis:[named-uuid row3683ef96_0920_4e07_a15a_aa44212c910b] name:3e3edded-a3f2-4cab-b158-da88da75a095] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row642a98ef_0e7b_429a_b883_12d6c2c5cf5c UUID:<nil> Comment: Durable:false} {Op:comment Table: Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName: UUID:<nil> Comment:ovn-controller
ovn-controller: registering chassis '3e3edded-a3f2-4cab-b158-da88da75a095' Durable:false}]}

 transact.go:1117] failed validation of table OVN_Southbound/Chassis: Value is invalid for column other_config

**Comment by roytman** [comment]
**Another example:**

transact.go:269] create new transaction with request params: &{DBName:OVN_Southbound Operations:[{Op:insert Table:Encap Row:map[chassis_name:3e3edded-a3f2-4cab-b158-da88da75a095 ip:172.18.0.2 options:[map [[csum true]]] type:geneve] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row1fcbcaec_199c_4eee_aff0_a465cdb948d1 UUID:<nil> Comment: Durable:false} {Op:insert Table:Chassis Row:map[encaps:[named-uuid row1fcbcaec_199c_4eee_aff0_a465cdb948d1] external_ids:[map [[datapath-type ] [iface-types bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan] [is-interconn false] [ovn-bridge-mappings ] [ovn-chassis-mac-mappings ] [ovn-cms-options ] [ovn-enable-lflow-cache true] [ovn-monitor-all true] [port-up-notif true]]] hostname:ovn-control-plane name:3e3edded-a3f2-4cab-b158-da88da75a095 other_config:[map [[datapath-type ] [iface-types bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan] [is-interconn false] [ovn-bridge-mappings ] [ovn-chassis-mac-mappings ] [ovn-cms-options ] [ovn-enable-lflow-cache true] [ovn-monitor-all true] [port-up-notif true]]]] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row05d68876_e6e9_48c7_998a_5d8e45153fde UUID:<nil> Comment: Durable:false} {Op:insert Table:Chassis_Private Row:map[chassis:[named-uuid row05d68876_e6e9_48c7_998a_5d8e45153fde] name:3e3edded-a3f2-4cab-b158-da88da75a095] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row132a031f_9333_4365_9fbb_e20dd4822ae9 UUID:<nil> Comment: Durable:false} {Op:comment Table: Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName: UUID:<nil> Comment:ovn-controller
ovn-controller: registering chassis '3e3edded-a3f2-4cab-b158-da88da75a095' Durable:false}]}

 transact.go:1117] failed validation of table OVN_Southbound/Encap: Value is invalid for column options

**Comment by roytman** [comment]
maybe this one is better as a starting point
I0515 11:44:40.019945      12 transact.go:269] create new transaction with request params: &{DBName:OVN_Northbound Operations:[{Op:wait Table:NB_Global Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until:== UUIDName: UUI
D:<nil> Comment: Durable:false} {Op:insert Table:NB_Global Row:map[options:[map [[mac_prefix a6:ed:71] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 12:50:bf:9d:6d:72]]]] Rows:[] Columns:[] Mutati
ons:[] Timeout:0 Where:[] Until: UUIDName:row3aaf6f6c_3228_494c_82de_012f9cc20904 UUID:<nil> Comment: Durable:false} {Op:comment Table: Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName: UUID:<nil> Comment:ov
n-northd Durable:false}]}

```
{
  DBName: OVN_NorthboundOperations: [
    {
      Op: waitTable: NB_GlobalRow: map[
        
      ]Rows: [
        
      ]Columns: [
        
      ]Mutations: [
        
      ]Timeout: 0Where: [
        
      ]Until: ==UUIDName: UUID: <nil>Comment: Durable: false
    }{
      Op: insertTable: NB_GlobalRow: map[
        options: [
          map[
            [
              mac_prefixa6: ed: 71
            ][
              max_tunid16711680
            ][
              northd_internal_version20.12.0-20.16.1-56.0
            ][
              svc_monitor_mac12: 50: bf: 9d: 6d: 72
            ]
          ]
        ]
      ]Rows: [
        
      ]Columns: [
        
      ]Mutations: [
        
      ]Timeout: 0Where: [
        
      ]Until: UUIDName: row3aaf6f6c_3228_494c_82de_012f9cc20904UUID: <nil>Comment: Durable: false
    }{
      Op: commentTable: Row: map[
        
      ]Rows: [
        
      ]Columns: [
        
      ]Mutations: [
        
      ]Timeout: 0Where: [
        
      ]Until: UUIDName: UUID: <nil>Comment: ovn-northdDurable: false
    }
  ]
}```

E0515 11:44:40.022498      12 transact.go:1117] failed validation of table OVN_Northbound/NB_Global: Value is invalid for column options

**Comment by hunchback** [comment]
@roytman the `Until` statement appears to be malformed:

```
Until: UUIDName: row3aaf6f6c_3228_494c_82de_012f9cc20904UUID: <nil>
```

can you send me the original JSON RPC?

**Comment by hunchback** [comment]
Schema is:

```
"options": {
                    "type": {"key": "string", "value": "string",
                             "min": 0, "max": "unlimited"}},
```

**Comment by roytman** [comment]
See this log message, looks like another "feature" of OVSDB JSON

I0515 23:20:01.802090      13 handler.go:38] Transact request, parameters [OVN_Northbound map[op:wait rows:[] table:NB_Global timeout:0 until:== where:[]] map[op:insert row:map[options:[map [[mac_prefix fa:4e:b8] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 1e:29:92:32:65:ea]]]] table:NB_Global uuid-name:rowe7100310_4498_4ce7_bed7_29efdc249605] map[comment:ovn-northd op:comment]]

I0515 23:20:01.808451      13 handler.go:47] Transact response {[{<nil> <nil> <nil> <nil> <nil>} {<nil> 0xc0001cf790 <nil> <nil> <nil>} {<nil> <nil> <nil> <nil> <nil>}] constraint violation}

**Comment by roytman** [comment]
0516 08:48:49.138779      13 transact.go:269] create new transaction with request params: &{DBName:OVN_Northbound Operations:[{Op:wait Table:NB_Global Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until:== UUIDName: UUI
D:<nil> Comment: Durable:false} {Op:insert Table:NB_Global Row:map[options:[map [[mac_prefix be:b7:8e] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 1e:9d:25:7c:1e:01]]]] Rows:[] Columns:[] Mutati
ons:[] Timeout:0 Where:[] Until: UUIDName:rowe4100838_d8d1_42b5_9b2b_82fd39a2eecb UUID:<nil> Comment: Durable:false} {Op:comment Table: Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName: UUID:<nil> Comment:ov
n-northd Durable:false}]}

E0516 08:48:49.139682      13 transact.go:1117] failed validation of table OVN_Northbound/NB_Global: [database OVN_Northbound] [table NB_Global] [column options] expected map: [map [[mac_prefix be:b7:8e] [max_tunid 16711680] [northd_in
ternal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 1e:9d:25:7c:1e:01]]]

**Comment by roytman** [comment]
I0516 09:36:42.134513      11 transact.go:269] create new transaction with request params: &{DBName:OVN_Northbound Operations:[{Op:wait Table:NB_Global Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until:== UUIDName: UUID:<nil> Comment: Durable:false} {Op:insert Table:NB_Global Row:map[options:[map [[mac_prefix 12:6f:dc] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 46:0a:89:b5:c7:a4]]]] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName:row5ee9567a_9361_4329_b7b7_bd5349c718f3 UUID:<nil> Comment: Durable:false} {Op:comment Table: Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:0 Where:[] Until: UUIDName: UUID:<nil> Comment:ov
n-northd Durable:false}]}

E0516 09:36:42.135231      11 transact.go:1118] failed validation of table OVN_Northbound/NB_Global: [database OVN_Northbound] [table NB_Global] [column options] expected map: [map [[mac_prefix 12:6f:dc] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 46:0a:89:b5:c7:a4]]]

**Comment by roytman** [comment]
E0516 11:21:19.728741      12 transact.go:1117] failed validation of table OVN_Northbound/NB_Global: [database OVN_Northbound] [table NB_Global] [column options] expected map: [map [[mac_prefix 5e:9a:69] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac ea:dc:54:e8:8c:44]]]
E0516 11:21:19.737641      12 transact.go:1117] failed validation of table OVN_Northbound/NB_Global: [database OVN_Northbound] [table NB_Global] [column options] expected map: [map [[mac_prefix 2a:14:f6] [max_tunid 16711680] [northd_internal_version 20.12.0-20.16.1-56.0] [svc_monitor_mac 8a:e6:32:5b:59:4a]]]

**Comment by roytman** [comment]
fixed
