### ISSUE TITLE
Transaction timeout error

### ISSUE THREAD

**Issue by roytman** [IBM/ovsdb-etcd#156]
OVSDB_etcd returns `handler.go:50] Transact response {"result":[{"error":"timed out"},{},{}],"error":"timed out"}
`
To requests:
`transact.go:473] new transaction [with size 3]: {"dbname":"OVN_Northbound","operations":[{"op":"wait","table":"Logical_Switch","rows":[{"load_balancer":["uuid","b17e4b13-b27b-4324-9b20-fbd8d7f6f1b9"]}],"columns":["load_balancer"],"timeout":0,"where":[["_uuid","==",["uuid","085c6d92-500e-42fb-baf1-b53384454c16"]]],"until":"=="},{"op":"update","table":"Logical_Switch","row":{"load_balancer":["set",[["uuid","1e89e1dd-9358-4531-a021-a0eaa20f2fc8"],["uuid","b17e4b13-b27b-4324-9b20-fbd8d7f6f1b9"]]]},"where":[["_uuid","==",["uuid","085c6d92-500e-42fb-baf1-b53384454c16"]]]},{"op":"comment","comment":"ovs-nbctl: run -- add logical_switch ovn-worker load_balancer 1e89e1dd-9358-4531-a021-a0eaa20f2fc8"}]}`

**Comment by hunchback** [comment]
the error 'timed out' is E_TIMEOUT in the `pkg/ovsdb/transact.go:doWait` implementation, which is coming from the implementation of the `isEqualRows` implementation.

a pretty json failing is:

```
{
   "op":"wait",
   "table":"Logical_Switch",
   "rows":[
      {
         "load_balancer":[
            "uuid",
            "b17e4b13-b27b-4324-9b20-fbd8d7f6f1b9"
         ]
      }
   ],
   "columns":[
      "load_balancer"
   ],
   "timeout":0,
   "where":[
      [
         "_uuid",
         "==",
         [
            "uuid",
            "085c6d92-500e-42fb-baf1-b53384454c16"
         ]
      ]
   ],
   "until":"=="
}
```

**Comment by hunchback** [comment]
fixed
