### ISSUE TITLE
"duplicate monitor ID" message 

### ISSUE THREAD

**Issue by hunchback** [IBM/ovsdb-etcd#197]
```
2021-06-07T20:03:55.570Z|53384|jsonrpc|DBG|tcp:172.18.0.2:6642: send request, method="monitor", params=["OVN_Southbound",["monid","OVN_Southbound"],{"RBAC_Role":[{"columns":["name","permissions"]}],"RBAC_Permission":[{"columns":["authorization","insert_delete","table","update"]}],"FDB":[{"columns":["dp_key","mac","port_key"]}],"SB_Global":[{"columns":["ipsec","nb_cfg","options"]}],"Meter_Band":[{"columns":["action","burst_size","rate"]}],"Port_Binding":[{"columns":["chassis","datapath","external_ids","gateway_chassis","ha_chassis_group","logical_port","mac","nat_addresses","options","parent_port","tag","tunnel_key","type","up","virtual_parent"]}],"Meter":[{"columns":["bands","name","unit"]}],"Address_Set":[{"columns":["addresses","name"]}],"HA_Chassis_Group":[{"columns":["external_ids","ha_chassis","name","ref_chassis"]}],"BFD":[{"columns":["detect_mult","disc","dst_ip","logical_port","min_rx","min_tx","src_port","status"]}],"Load_Balancer":[{"columns":["datapaths","external_ids","name","options","protocol","vips"]}],"DNS":[{"columns":["datapaths","external_ids","records"]}],"Logical_DP_Group":[{"columns":["datapaths"]}],"IP_Multicast":[{"columns":["datapath","enabled","eth_src","idle_timeout","ip4_src","ip6_src","querier","query_interval","query_max_resp","table_size"]}],"Encap":[{"columns":["type"]}],"Gateway_Chassis":[{"columns":["chassis","external_ids","name","options","priority"]}],"DHCPv6_Options":[{"columns":["code","name","type"]}],"Chassis_Private":[{"columns":["chassis","name","nb_cfg","nb_cfg_timestamp"]}],"HA_Chassis":[{"columns":["chassis","external_ids","priority"]}],"IGMP_Group":[{"columns":["address","chassis","datapath","ports"]}],"Service_Monitor":[{"columns":["external_ids","ip","logical_port","options","port","protocol","src_ip","src_mac","status"]}],"Chassis":[{"columns":["encaps","name","other_config"]}],"Port_Group":[{"columns":["name","ports"]}],"Multicast_Group":[{"columns":["datapath","name","ports","tunnel_key"]}],"MAC_Binding":[{"columns":["datapath","ip","logical_port","mac"]}],"Logical_Flow":[{"columns":["actions","logical_datapath","logical_dp_group","match","pipeline","priority","table_id"]}],"Datapath_Binding":[{"columns":["external_ids","load_balancers","tunnel_key"]}],"DHCP_Options":[{"columns":["code","name","type"]}]}], id=3615
2021-06-07T20:03:55.571Z|53385|ovsdb_cs|DBG|tcp:172.18.0.2:6642: DATA_MONITOR_COND_REQUESTED -> DATA_MONITOR_REQUESTED at lib/ovsdb-cs.c:501
2021-06-07T20:03:55.589Z|53386|poll_loop|DBG|wakeup due to [POLLIN] on fd 11 (172.18.0.2:57600<->172.18.0.2:6642) at lib/stream-fd.c:157 (0% CPU usage)
2021-06-07T20:03:55.589Z|53387|jsonrpc|DBG|tcp:172.18.0.2:6642: received error, error={"message":"duplicate json-value"}, id=3615
2021-06-07T20:03:55.590Z|53388|ovsdb_cs|INFO|tcp:172.18.0.2:6642: received unexpected error response in DATA_MONITOR_REQUESTED state: {"error":{"message":"duplicate json-value"},"id":3615,"result":null}
2021-06-07T20:03:55.590Z|53389|reconnect|DBG|tcp:172.18.0.2:6642: entering RECONNECT
2021-06-07T20:03:55.590Z|53390|ovsdb_cs|DBG|tcp:172.18.0.2:6642: DATA_MONITOR_REQUESTED -> RETRY at lib/ovsdb-cs.c:441
2021-06-07T20:03:55.590Z|53391|poll_loop|DBG|wakeup due to 0-ms timeout at lib/reconnect.c:664 (0% CPU usage)
2021-06-07T20:03:55.590Z|53392|reconnect|DBG|tcp:172.18.0.2:6642: entering BACKOFF
```

**Comment by roytman** [comment]
It happens not only with ovn-northd but with other clients as well, e.g. ovn-controller and with other monitor messages. The error message was changed, according to the OVSDB implementation. 
Change the issue name.

**Comment by roytman** [comment]
Logs between sn-ovndb-etcd and ovn-controller

ovn-controller:
`2021-06-07T14:31:14.250Z|00006|main|INFO|OVNSB IDL reconnected, force recompute.
2021-06-07T14:31:15.186Z|00007|reconnect|INFO|tcp:172.18.0.4:6642: connecting...
2021-06-07T14:31:15.186Z|00008|reconnect|INFO|tcp:172.18.0.4:6642: connection attempt failed (Connection refused)
2021-06-07T14:31:16.187Z|00009|reconnect|INFO|tcp:172.18.0.4:6642: connecting...
2021-06-07T14:31:16.187Z|00010|reconnect|INFO|tcp:172.18.0.4:6642: connection attempt failed (Connection refused)
2021-06-07T14:31:16.187Z|00011|reconnect|INFO|tcp:172.18.0.4:6642: waiting 2 seconds before reconnect
2021-06-07T14:31:18.187Z|00012|reconnect|INFO|tcp:172.18.0.4:6642: connecting...
2021-06-07T14:31:18.187Z|00013|reconnect|INFO|tcp:172.18.0.4:6642: connection attempt failed (Connection refused)
2021-06-07T14:31:18.187Z|00014|reconnect|INFO|tcp:172.18.0.4:6642: waiting 4 seconds before reconnect
2021-06-07T14:31:22.191Z|00015|reconnect|INFO|tcp:172.18.0.4:6642: connecting...
2021-06-07T14:31:22.191Z|00016|reconnect|INFO|tcp:172.18.0.4:6642: connection attempt failed (Connection refused)
2021-06-07T14:31:22.192Z|00017|reconnect|INFO|tcp:172.18.0.4:6642: continuing to reconnect in the background but suppressing further logging
2021-06-07T14:31:29.299Z|00018|memory|INFO|3884 kB peak resident set size after 15.1 seconds
2021-06-07T14:31:30.192Z|00019|reconnect|INFO|tcp:172.18.0.4:6642: connected
2021-06-07T14:31:30.210Z|00020|ovsdb_cs|INFO|tcp:172.18.0.4:6642: received unexpected error response in DATA_MONITOR_REQUESTED state: {"error":{"error":"duplicate monitor ID"},"id":12,"result":null}
2021-06-07T14:31:38.218Z|00021|reconnect|INFO|tcp:172.18.0.4:6642: connected
`

sb-ovndb-etcd:

> I0607 14:31:30.192318      12 server.go:151] new connection from 172.18.0.2:45550
I0607 14:31:30.192352      12 server.go:269] read from 172.18.0.2:45550, i= 51 err=<nil>

I0607 14:31:30.192401      12 service.go:237] GetSchema request, parameters [_Server]
I0607 14:31:30.192581      12 server.go:275] write to 172.18.0.2:45550, i= 528 err=<nil>

I0607 14:31:30.192780      12 server.go:269] read from 172.18.0.2:45550, i= 161 err=<nil>

I0607 14:31:30.192879      12 handler.go:177] MonitorCond request from 172.18.0.2:45550, param [_Server [monid _Server] map[Database:[map[columns:[name model connected leader schema cid index]]]]]
I0607 14:31:30.200977      12 handler.go:184] MonitorCond response to 172.18.0.2:45550, params [_Server [monid _Server] map[Database:[map[columns:[name model connected leader schema cid index]]]]], err <nil>
I0607 14:31:30.201284      12 handler.go:215] SetDbChangeAware request from 172.18.0.2:45550, param [true]
I0607 14:31:30.201497      12 handler.go:199] MonitorCondSince request from 172.18.0.2:45550, parameters [OVN_Southbound [monid OVN_Southbound] map[Address_Set:[map[columns:[addresses name]]] BFD:[map[columns:[detect_mult disc dst_ip external_ids logical_port min_rx min_tx options src_port status]]] Chassis:[map[columns:[encaps external_ids hostname name nb_cfg other_config transport_zones vtep_logical_switches]]] Chassis_Private:[map[columns:[chassis name nb_cfg nb_cfg_timestamp] where:[true]]] Controller_Event:[map[columns:[chassis event_info event_type seq_num] where:[true]]] DHCP_Options:[map[columns:[code name type]]] DHCPv6_Options:[map[columns:[code name type]]] DNS:[map[columns:[datapaths external_ids records] where:[true]]] Datapath_Binding:[map[columns:[external_ids load_balancers tunnel_key]]] Encap:[map[columns:[chassis_name ip options type]]] FDB:[map[columns:[dp_key mac port_key]]] Gateway_Chassis:[map[columns:[chassis name options priority]]] HA_Chassis:[map[columns:[chassis priority]]] HA_Chassis_Group:[map[columns:[ha_chassis name ref_chassis]]] IGMP_Group:[map[columns:[address chassis datapath ports] where:[true]]] IP_Multicast:[map[columns:[datapath enabled eth_src idle_timeout ip4_src ip6_src querier query_interval query_max_resp seq_no table_size] where:[true]]] Load_Balancer:[map[columns:[datapaths external_ids name options protocol vips]]] Logical_DP_Group:[map[columns:[datapaths] where:[true]]] Logical_Flow:[map[columns:[actions logical_datapath logical_dp_group match pipeline priority table_id] where:[true]]] MAC_Binding:[map[columns:[datapath ip logical_port mac] where:[true]]] Meter:[map[columns:[bands name unit]]] Meter_Band:[map[columns:[action burst_size rate]]] Multicast_Group:[map[columns:[datapath name ports tunnel_key] where:[true]]] Port_Binding:[map[columns:[chassis datapath encap gateway_chassis ha_chassis_group logical_port mac nat_addresses options parent_port tag tunnel_key type up virtual_parent] where:[true]]] Port_Group:[map[columns:[name ports]]] RBAC_Permission:[map[columns:[authorization insert_delete table update]]] RBAC_Role:[map[columns:[name permissions]]] SB_Global:[map[columns:[connections ipsec nb_cfg options ssl]]] SSL:[map[columns:[bootstrap_ca_cert ca_cert certificate private_key ssl_ciphers ssl_protocols]]] Service_Monitor:[map[columns:[external_ids ip logical_port options port protocol src_ip src_mac status]]]] 00000000-0000-0000-0000-000000000000]
I0607 14:31:30.202921      12 server.go:275] write to 172.18.0.2:45550, i= 30831 err=<nil>

I0607 14:31:30.205071      12 server.go:269] read from 172.18.0.2:45550, i= 512 err=<nil>

I0607 14:31:30.205120      12 server.go:269] read from 172.18.0.2:45550, i= 1024 err=<nil>

I0607 14:31:30.205157      12 server.go:269] read from 172.18.0.2:45550, i= 1250 err=<nil>

I0607 14:31:30.205510      12 handler.go:215] SetDbChangeAware request from 172.18.0.2:45550, param [true]
I0607 14:31:30.206122      12 handler.go:199] MonitorCondSince request from 172.18.0.2:45550, parameters [OVN_Southbound [monid OVN_Southbound] map[Address_Set:[map[columns:[addresses name]]] BFD:[map[columns:[detect_mult disc dst_ip external_ids logical_port min_rx min_tx options src_port status]]] Chassis:[map[columns:[encaps external_ids hostname name nb_cfg other_config transport_zones vtep_logical_switches]]] Chassis_Private:[map[columns:[chassis name nb_cfg nb_cfg_timestamp] where:[true]]] Controller_Event:[map[columns:[chassis event_info event_type seq_num] where:[true]]] DHCP_Options:[map[columns:[code name type]]] DHCPv6_Options:[map[columns:[code name type]]] DNS:[map[columns:[datapaths external_ids records] where:[true]]] Datapath_Binding:[map[columns:[external_ids load_balancers tunnel_key]]] Encap:[map[columns:[chassis_name ip options type]]] FDB:[map[columns:[dp_key mac port_key]]] Gateway_Chassis:[map[columns:[chassis name options priority]]] HA_Chassis:[map[columns:[chassis priority]]] HA_Chassis_Group:[map[columns:[ha_chassis name ref_chassis]]] IGMP_Group:[map[columns:[address chassis datapath ports] where:[true]]] IP_Multicast:[map[columns:[datapath enabled eth_src idle_timeout ip4_src ip6_src querier query_interval query_max_resp seq_no table_size] where:[true]]] Load_Balancer:[map[columns:[datapaths external_ids name options protocol vips]]] Logical_DP_Group:[map[columns:[datapaths] where:[true]]] Logical_Flow:[map[columns:[actions logical_datapath logical_dp_group match pipeline priority table_id] where:[true]]] MAC_Binding:[map[columns:[datapath ip logical_port mac] where:[true]]] Meter:[map[columns:[bands name unit]]] Meter_Band:[map[columns:[action burst_size rate]]] Multicast_Group:[map[columns:[datapath name ports tunnel_key] where:[true]]] Port_Binding:[map[columns:[chassis datapath encap gateway_chassis ha_chassis_group logical_port mac nat_addresses options parent_port tag tunnel_key type up virtual_parent] where:[true]]] Port_Group:[map[columns:[name ports]]] RBAC_Permission:[map[columns:[authorization insert_delete table update]]] RBAC_Role:[map[columns:[name permissions]]] SB_Global:[map[columns:[connections ipsec nb_cfg options ssl]]] SSL:[map[columns:[bootstrap_ca_cert ca_cert certificate private_key ssl_ciphers ssl_protocols]]] Service_Monitor:[map[columns:[external_ids ip logical_port options port protocol src_ip src_mac status]]]] 00000000-0000-0000-0000-000000000000]
I0607 14:31:30.206722      12 server.go:275] write to 172.18.0.2:45550, i= 21 err=<nil>

E0607 14:31:30.207174      12 handler.go:202] MonitorCondSince from remote 172.18.0.2:45550 got an error: duplicate monitor ID
I0607 14:31:30.207292      12 server.go:275] write to 172.18.0.2:45550, i= 49 err=<nil>

I0607 14:31:30.207778      12 server.go:269] read from 172.18.0.2:45550, i= 2686 err=<nil>
I0607 14:31:30.208417      12 handler.go:177] MonitorCond request from 172.18.0.2:45550, param [OVN_Southbound [monid OVN_Southbound] map[Address_Set:[map[columns:[addresses name]]] BFD:[map[columns:[detect_mult disc dst_ip external_ids logical_port min_rx min_tx options src_port status]]] Chassis:[map[columns:[encaps external_ids hostname name nb_cfg other_config transport_zones vtep_logical_switches]]] Chassis_Private:[map[columns:[chassis name nb_cfg nb_cfg_timestamp] where:[true]]] Controller_Event:[map[columns:[chassis event_info event_type seq_num] where:[true]]] DHCP_Options:[map[columns:[code name type]]] DHCPv6_Options:[map[columns:[code name type]]] DNS:[map[columns:[datapaths external_ids records] where:[true]]] Datapath_Binding:[map[columns:[external_ids load_balancers tunnel_key]]] Encap:[map[columns:[chassis_name ip options type]]] FDB:[map[columns:[dp_key mac port_key]]] Gateway_Chassis:[map[columns:[chassis name options priority]]] HA_Chassis:[map[columns:[chassis priority]]] HA_Chassis_Group:[map[columns:[ha_chassis name ref_chassis]]] IGMP_Group:[map[columns:[address chassis datapath ports] where:[true]]] IP_Multicast:[map[columns:[datapath enabled eth_src idle_timeout ip4_src ip6_src querier query_interval query_max_resp seq_no table_size] where:[true]]] Load_Balancer:[map[columns:[datapaths external_ids name options protocol vips]]] Logical_DP_Group:[map[columns:[datapaths] where:[true]]] Logical_Flow:[map[columns:[actions logical_datapath logical_dp_group match pipeline priority table_id] where:[true]]] MAC_Binding:[map[columns:[datapath ip logical_port mac] where:[true]]] Meter:[map[columns:[bands name unit]]] Meter_Band:[map[columns:[action burst_size rate]]] Multicast_Group:[map[columns:[datapath name ports tunnel_key] where:[true]]] Port_Binding:[map[columns:[chassis datapath encap gateway_chassis ha_chassis_group logical_port mac nat_addresses options parent_port tag tunnel_key type up virtual_parent] where:[true]]] Port_Group:[map[columns:[name ports]]] RBAC_Permission:[map[columns:[authorization insert_delete table update]]] RBAC_Role:[map[columns:[name permissions]]] SB_Global:[map[columns:[connections ipsec nb_cfg options ssl]]] SSL:[map[columns:[bootstrap_ca_cert ca_cert certificate private_key ssl_ciphers ssl_protocols]]] Service_Monitor:[map[columns:[external_ids ip logical_port options port protocol src_ip src_mac status]]]]]
E0607 14:31:30.208928      12 handler.go:180] MonitorCond from remote 172.18.0.2:45550 got an error: duplicate monitor ID
I0607 14:31:30.209148      12 server.go:275] write to 172.18.0.2:45550, i= 50 err=<nil>

I0607 14:31:30.209375      12 server.go:269] read from 172.18.0.2:45550, i= 2531 err=<nil>
I0607 14:31:30.209839      12 handler.go:77] Monitor request from 172.18.0.2:45550, params [OVN_Southbound [monid OVN_Southbound] map[Address_Set:[map[columns:[addresses name]]] BFD:[map[columns:[detect_mult disc dst_ip external_ids logical_port min_rx min_tx options src_port status]]] Chassis:[map[columns:[encaps external_ids hostname name nb_cfg other_config transport_zones vtep_logical_switches]]] Chassis_Private:[map[columns:[chassis name nb_cfg nb_cfg_timestamp]]] Controller_Event:[map[columns:[chassis event_info event_type seq_num]]] DHCP_Options:[map[columns:[code name type]]] DHCPv6_Options:[map[columns:[code name type]]] DNS:[map[columns:[datapaths external_ids records]]] Datapath_Binding:[map[columns:[external_ids load_balancers tunnel_key]]] Encap:[map[columns:[chassis_name ip options type]]] FDB:[map[columns:[dp_key mac port_key]]] Gateway_Chassis:[map[columns:[chassis name options priority]]] HA_Chassis:[map[columns:[chassis priority]]] HA_Chassis_Group:[map[columns:[ha_chassis name ref_chassis]]] IGMP_Group:[map[columns:[address chassis datapath ports]]] IP_Multicast:[map[columns:[datapath enabled eth_src idle_timeout ip4_src ip6_src querier query_interval query_max_resp seq_no table_size]]] Load_Balancer:[map[columns:[datapaths external_ids name options protocol vips]]] Logical_DP_Group:[map[columns:[datapaths]]] Logical_Flow:[map[columns:[actions logical_datapath logical_dp_group match pipeline priority table_id]]] MAC_Binding:[map[columns:[datapath ip logical_port mac]]] Meter:[map[columns:[bands name unit]]] Meter_Band:[map[columns:[action burst_size rate]]] Multicast_Group:[map[columns:[datapath name ports tunnel_key]]] Port_Binding:[map[columns:[chassis datapath encap gateway_chassis ha_chassis_group logical_port mac nat_addresses options parent_port tag tunnel_key type up virtual_parent]]] Port_Group:[map[columns:[name ports]]] RBAC_Permission:[map[columns:[authorization insert_delete table update]]] RBAC_Role:[map[columns:[name permissions]]] SB_Global:[map[columns:[connections ipsec nb_cfg options ssl]]] SSL:[map[columns:[bootstrap_ca_cert ca_cert certificate private_key ssl_ciphers ssl_protocols]]] Service_Monitor:[map[columns:[external_ids ip logical_port options port protocol src_ip src_mac status]]]]]
E0607 14:31:30.210507      12 handler.go:80] Monitor from 172.18.0.2:45550, params [OVN_Southbound [monid OVN_Southbound] map[Address_Set:[map[columns:[addresses name]]] BFD:[map[columns:[detect_mult disc dst_ip external_ids logical_port min_rx min_tx options src_port status]]] Chassis:[map[columns:[encaps external_ids hostname name nb_cfg other_config transport_zones vtep_logical_switches]]] Chassis_Private:[map[columns:[chassis name nb_cfg nb_cfg_timestamp]]] Controller_Event:[map[columns:[chassis event_info event_type seq_num]]] DHCP_Options:[map[columns:[code name type]]] DHCPv6_Options:[map[columns:[code name type]]] DNS:[map[columns:[datapaths external_ids records]]] Datapath_Binding:[map[columns:[external_ids load_balancers tunnel_key]]] Encap:[map[columns:[chassis_name ip options type]]] FDB:[map[columns:[dp_key mac port_key]]] Gateway_Chassis:[map[columns:[chassis name options priority]]] HA_Chassis:[map[columns:[chassis priority]]] HA_Chassis_Group:[map[columns:[ha_chassis name ref_chassis]]] IGMP_Group:[map[columns:[address chassis datapath ports]]] IP_Multicast:[map[columns:[datapath enabled eth_src idle_timeout ip4_src ip6_src querier query_interval query_max_resp seq_no table_size]]] Load_Balancer:[map[columns:[datapaths external_ids name options protocol vips]]] Logical_DP_Group:[map[columns:[datapaths]]] Logical_Flow:[map[columns:[actions logical_datapath logical_dp_group match pipeline priority table_id]]] MAC_Binding:[map[columns:[datapath ip logical_port mac]]] Meter:[map[columns:[bands name unit]]] Meter_Band:[map[columns:[action burst_size rate]]] Multicast_Group:[map[columns:[datapath name ports tunnel_key]]] Port_Binding:[map[columns:[chassis datapath encap gateway_chassis ha_chassis_group logical_port mac nat_addresses options parent_port tag tunnel_key type up virtual_parent]]] Port_Group:[map[columns:[name ports]]] RBAC_Permission:[map[columns:[authorization insert_delete table update]]] RBAC_Role:[map[columns:[name permissions]]] SB_Global:[map[columns:[connections ipsec nb_cfg options ssl]]] SSL:[map[columns:[bootstrap_ca_cert ca_cert certificate private_key ssl_ciphers ssl_protocols]]] Service_Monitor:[map[columns:[external_ids ip logical_port options port protocol src_ip src_mac status]]]]] got an error: duplicate monitor ID
I0607 14:31:30.210686      12 server.go:275] write to 172.18.0.2:45550, i= 50 err=<nil>

I0607 14:31:30.210979      12 server.go:269] read from 172.18.0.2:45550, i= 0 err=EOF

I0607 14:31:30.210988      12 server.go:280] connection from 172.18.0.2:45550 called close
I0607 14:31:30.211122      12 server.go:157] connection from 172.18.0.2:45550, stopped false closed true, success true, err <nil>
I0607 14:31:30.211128      12 handler.go:236] CLEAN UP do something from 172.18.0.2:45550
I0607 14:31:30.246410      12 handler.go:44] Transact request from 172.18.0.2:45550, params [OVN_Southbound map[op:insert row:map[chassis:[named-uuid rowa558c97b_13d8_4af0_ba53_e155662f85b7] name:b604b60e-c5b0-4b53-8eb9-e82b92b4d567] table:Chassis_Private uuid-name:rowd7ae0ff0_5e78_4a4a_9fc6_95b78a764a29] map[op:insert row:map[chassis_name:b604b60e-c5b0-4b53-8eb9-e82b92b4d567 ip:172.18.0.3 options:[map [[csum true]]] type:geneve] table:Encap uuid-name:row9e5d39c0_425e_4041_960d_76880c08eb64] map[op:insert row:map[encaps:[named-uuid row9e5d39c0_425e_4041_960d_76880c08eb64] external_ids:[map [[datapath-type ] [iface-types bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan] [is-interconn false] [ovn-bridge-mappings ] [ovn-chassis-mac-mappings ] [ovn-cms-options ] [ovn-enable-lflow-cache true] [ovn-limit-lflow-cache ] [ovn-memlimit-lflow-cache-kb ] [ovn-monitor-all true] [port-up-notif true]]] hostname:ovn-worker name:b604b60e-c5b0-4b53-8eb9-e82b92b4d567 other_config:[map [[datapath-type ] [iface-types bareudp,erspan,geneve,gre,gtpu,internal,ip6erspan,ip6gre,lisp,patch,stt,system,tap,vxlan] [is-interconn false] [ovn-bridge-mappings ] [ovn-chassis-mac-mappings ] [ovn-cms-options ] [ovn-enable-lflow-cache true] [ovn-limit-lflow-cache ] [ovn-memlimit-lflow-cache-kb ] [ovn-monitor-all true] [port-up-notif true]]]] table:Chassis uuid-name:rowa558c97b_13d8_4af0_ba53_e155662f85b7] map[comment:ovn-controller
ovn-controller: registering chassis 'b604b60e-c5b0-4b53-8eb9-e82b92b4d567' op:comment]]
I0607 14:31:30.246475      12 handler.go:46] Transact request from 172.18.0.2:45550, the handler is closed

**Comment by roytman** [comment]
Looks like we have wrong message handling:
1. probably our jrpc client tries to recall us with an error messages
2. EOF on the read channel.

**Comment by roytman** [comment]
Fixed by https://github.com/IBM/ovsdb-etcd/pull/204
