### ISSUE TITLE
Transaction creates notification event with a wrong previous value set

### ISSUE THREAD

**Issue by roytman** [IBM/ovsdb-etcd#250]
A new transactin:

> I0621 20:26:04.635991      15 handler.go:55]  "msg"="transact" "client"="172.18.0.3:46606" "hid"="mXc3MmAxhTkDeHwuXP5ZXA" "id"="28" "params"=["OVN_Northbound",{"columns":["addresses"],"op":"wait","rows":[{"addresses":["set",["10.24      4.0.2","100.64.0.2"]]}],"table":"Address_Set","timeout":0,"until":"==","where":[["_uuid","==",["uuid","d6b38f84-aa5a-4391-a59a-07820b70fa77"]]]},{"op":"update","row":{"addresses":["set",["10.244.0.2","10.244.1.2","100.64.0.2","100.      64.0.3"]]},"table":"Address_Set","where":[["_uuid","==",["uuid","d6b38f84-aa5a-4391-a59a-07820b70fa77"]]]},{"comment":"ovs-nbctl: run -- add address_set d6b38f84-aa5a-4391-a59a-07820b70fa77 addresses \"\\\"10.244.1.2\\\" \\\"100.64      .0.3\\\"\"","op":"comment"}]

I0621 20:26:04.636119      15 transact.go:603]  "msg"="new transaction" "client"="172.18.0.3:46606" "hid"="mXc3MmAxhTkDeHwuXP5ZXA" "id"="28" "request"={"dbname":"OVN_Northbound","operations":[{"op":"wait","table":"Address_Set","row      s":[{"addresses":["set",["10.244.0.2","100.64.0.2"]]}],"columns":["addresses"],"timeout":0,"where":[["_uuid","==",["uuid","d6b38f84-aa5a-4391-a59a-07820b70fa77"]]],"until":"=="},{"op":"update","table":"Address_Set","row":{"addresse      s":["set",["10.244.0.2","10.244.1.2","100.64.0.2","100.64.0.3"]]},"where":[["_uuid","==",["uuid","d6b38f84-aa5a-4391-a59a-07820b70fa77"]]]},{"op":"comment","comment":"ovs-nbctl: run -- add address_set d6b38f84-aa5a-4391-a59a-07820b      70fa77 addresses \"\\\"10.244.1.2\\\" \\\"100.64.0.3\\\"\""}]} "size"=3

Row comparison

> I0621 20:26:04.637068      15 transact.go:2015]  "msg"="checking row equal" "client"="172.18.0.3:46606" "hid"="mXc3MmAxhTkDeHwuXP5ZXA" "id"="28" "row"={"_uuid":["uuid","d6b38f84-aa5a-4391-a59a-07820b70fa77"],"_version":["uuid","ba5      740cc-bc94-4426-bade-2b9b9afc1e18"],"addresses":["set",["10.244.0.2","100.64.0.2"]],"external_ids":["map",[["name","ovn-host-network_v4"]]],"name":"a6173908967601696363"} "expected"={"addresses":["set",["10.244.0.2","100.64.0.2"]]}       "result"=true

The previous data in the notification event contains the updated address set, so the client was not updated, and it sent next messages with a wrong wait condition, and we got "timed out" error.

> I0621 20:26:04.640326      15 monitor.go:225]  "msg"="there is nothing to notify" "client"="172.18.0.3:46606" "hid"="mXc3MmAxhTkDeHwuXP5ZXA" "jsonValue"=["monid","OVN_Northbound"] "events"="[0xc0004afa00]"
 1616 I0621 20:26:04.640398      15 monitor.go:227]  "msg"="there is nothing to notify" "client"="172.18.0.3:46606" "hid"="mXc3MmAxhTkDeHwuXP5ZXA" "jsonValue"=["monid","OVN_Northbound"] "event"="&{Type:PUT 
Kv:key:\"ovsdb/nb/OVN_Northboun      d/Address_Set/d6b38f84-aa5a-4391-a59a-07820b70fa77\" create_revision:1 mod_revision:2 value:\"{\\\"_uuid\\\":[\\\"uuid\\\",\\\"d6b38f84-aa5a-4391-a59a-07820b70fa77\\\"],\\\"_version\\\":[\\\"uuid\\\",\\\"377ee5ab-a7c1-4143-8fa0-7c0f663fc293\\\"],\\\"addresses\\\":[\\\"set\\\",[\\\"10.244.0.2\\\",\\\"10.244.1.2\\\",\\\"100.64.0.2\\\",\\\"100.64.0.3\\\"]],\\\"external_ids\\\":[\\\"map\\\",[[\\\"name\\\",\\\"ovn-host-network_v4\\\"]]],\\\"name\\\":\\\"a61739089      67601696363\\\"}\"  
PrevKv:key:\"ovsdb/nb/OVN_Northbound/Address_Set/d6b38f84-aa5a-4391-a59a-07820b70fa77\" create_revision:1 mod_revision:1 value:\"{\\\"_uuid\\\":[\\\"uuid\\\",\\\"d6b38f84-aa5a-4391-a59a-07820b70fa77\\\"],\\\"_version\\\":[\\\"uuid\\\",\\\"377ee5ab-a7c1-4143-8fa0-7c0f663fc293\\\"],\\\"addresses\\\":[\\\"set\\\",[\\\"10.244.0.2\\\",\\\"10.244.1.2\\\",\\\"100.64.0.2\\\",\\\"100.64.0.3\\\"]],\\\"external_ids\\\":[\\\"map\\\",[[\\\"name\\\",\\      \"ovn-host-network_v4\\\"]]],\\\"name\\\":\\\"a6173908967601696363\\\"}\"  XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}"

**Comment by roytman** [comment]
we got the same behavior again

I0623 14:22:19.434641      14 transact.go:721]  "msg"="events transaction" "client"="172.18.0.2:36170" "hid"="4nHkKR9H9ZLLMqR8Zh8bif" "id"="16" "events"=[{"type":"\u0000","kv":{"key":"ovsdb/sb/OVN_Southbound/SB_Global/dd76ee24-943c-436a-a3db-f84ba28bfce5","create_revision":1,"mod_revision":2,"version":0,
"value":"{\"_uuid\":[\"uuid\",\"dd76ee24-943c-436a-a3db-f84ba28bfce5\"],\"_version\":[\"uuid\",\"7b697b62-7815-4557-954e-07be14779d05\"],\"connections\":[\"set\",[]],\"external_ids\":[\"map\",[]],\"ipsec\":false,\"nb_cfg\":0,\"options\":[\"map\",[[\"max_tunid\",\"16711680\"],[\"northd_internal_version\",\"21.03.1-20.16.1-56.0\"],[\"svc_monitor_mac\",\"26:e6:48:67:a2:27\"],[\"mac_prefix \",\"42:80:98\"]]],\"ssl\":[\"set\",[]]}","lease":0},
"prev_kv":{
"key":"ovsdb/sb/OVN_Southbound/SB_Global/dd76ee24-943c-436a-a3db-f84ba28bfce5","create_revision":1,"mod_revision":1,"version":0,
"value":"{\"_uuid\":[\"uuid\",\"dd76ee24-943c-436a-a3db-f84ba28bfce5\"],\"_version\":[\"uuid\",\"0a3cc5b4-c322-4e7b-b004-ba72add1de49\"],\"connections\":[\"set\",[]],\"external_ids\":[\"map\",[]],\"ipsec\":false,\"nb_cfg\":0,\"options\":[\"map\",[[\"svc_monitor_mac\",\"26:e6:48:67:a2:27\"],[\"mac_prefix\",\"42:80:98\"],[\"max_tunid\",\"16711680\"],[\"northd_internal_version\",\"21.03.1-20.16.1-56.0\"]]],\"ssl\":[\"set\",[]]}","lease":0}}] (edited)

**Comment by roytman** [comment]
git-commit"="289725bc7fa89536e981c0a5de73742463150ba5

**Comment by hunchback** [comment]
kv and prevkv have identical `options` map, while the expectation was that prev would be:

```
\"options\":[\"map\",[
[\"max_tunid\",\"16711680\"],
[\"northd_internal_version\",\"21.03.1-20.16.1-56.0\"],
[\"svc_monitor_mac\",\"26:e6:48:67:a2:27\"],
[\"mac_prefix \",\"42:80:98\"]]
]
```

expected prevkv:

```
\"options\":[\"map\",[
]
```

**Comment by roytman** [comment]
Transaction:
```
I0623 14:22:19.432184      14 handler.go:55]  "msg"="transact" "client"="172.18.0.2:36170" "hid"="4nHkKR9H9ZLLMqR8Zh8bif" "id"="16" "params"=["OVN_Southbound",

{"op":"update","
row":{"options":["map",[
["mac_prefix","42:80:98"],
["max_tunid","16711680"],
["northd_internal_version","21.03.1-20.16.1-56.0"],["svc_monitor_mac","26:e6:48:67:a2:27"]
]]},"table":"SB_Global","where":[["_uuid","==",["uuid","dd76ee24-943c-436a-a3db-f84ba28bfce5"]]]},{"comment":"ovn-northd",      "op":"comment"},{"lock":"ovn_northd","op":"assert"}]
  210 I0623 14:22:19.432266      14 transact.go:626]  "msg"="new transaction" "client"="172.18.0.2:36170" "hid"="4nHkKR9H9ZLLMqR8Zh8bif" "id"="16" "request"={"dbname":"OVN_Southbound","operations":[{"op":"update","table":"SB_Global","row      ":{"options":["map",[["mac_prefix","42:80:98"],["max_tunid","16711680"],["northd_internal_version","21.03.1-20.16.1-56.0"],["svc_monitor_mac","26:e6:48:67:a2:27"]]]},"where":[["_uuid","==",["uuid","dd76ee24-943c-436a-a3db-f84ba28bf      ce5"]]]},{"op":"comment","comment":"ovn-northd"},{"op":"assert"}]} "size"=3

**Comment by hunchback** [comment]
deep copy `copier.Copy` is not working:

```
(dlv) n
> github.com/ibm/ovsdb-etcd/pkg/ovsdb.(*Transaction).RowUpdate() ./transact.go:1537 (PC: 0xd72f89)
  1532: }
  1533:
  1534: func (txn *Transaction) RowUpdate(tableSchema *libovsdb.TableSchema, mapUUID MapUUID, currentRow *map[string]interface{}, update *map[string]interface{}) (*map[string]interface{}, error) {
  1535:         newRow := new(map[string]interface{})
  1536:         copier.Copy(newRow, currentRow)
=>1537:         for column, value := range *update {
  1538:                 columnSchema, err := tableSchema.LookupColumn(column)
  1539:                 if err != nil {
  1540:                         err = errors.New(E_CONSTRAINT_VIOLATION)
  1541:                         txn.log.Error(err, "failed column schema lookup", "column", column)
  1542:                         return nil, err
(dlv) p (*currentRow)["string"]
interface {}(github.com/ibm/ovsdb-etcd/pkg/libovsdb.OvsMap) {
        GoMap: map[interface {}]interface {} [
                *(*interface {})(0xc0001fe368): *(*interface {})(0xc0001fe3e8),
                *(*interface {})(0xc0001fe378): *(*interface {})(0xc0001fe3f8),
        ],}
(dlv) p (*newRow)["string"]
interface {}(github.com/ibm/ovsdb-etcd/pkg/libovsdb.OvsMap) {
        GoMap: map[interface {}]interface {} [
                *(*interface {})(0xc0001fe368): *(*interface {})(0xc0001fe3e8),
                *(*interface {})(0xc0001fe378): *(*interface {})(0xc0001fe3f8),
        ],}
(dlv)
```

**Comment by roytman** [comment]
we removed notifications created by transactions. Therefore, this issue is not relevant. Closing it.
