### ISSUE TITLE
Wrong delete  mutation

### ISSUE THREAD

**Issue by roytman** [IBM/ovsdb-etcd#259]
Transaction:

> {"dbname":"OVN_Northbound","operations":[{"op":"mutate","table":"Logical_Router",     "mutations":[["ports","delete",["set",[["uuid","0535086f-f347-4bee-a130-fb24034174e0"]]]],["ports","insert",["set",[["named-uuid","row6dc0b1cf_7554_4a41_a57e_2f6d51852632"]]]]],"where":[["_uuid","==",["uuid","d2b112f2-56b2-41bf-b9ce     -4c1641b93bf4"]]]},{"op":"insert","table":"Logical_Router_Port","row":{"mac":"0a:58:64:40:00:01","name":"rtoj-ovn_cluster_router","networks":"100.64.0.1/16"},"uuid-name":"row6dc0b1cf_7554_4a41_a57e_2f6d51852632"},{"op":"comment","co     mment":"ovs-nbctl: run -- --if-exists lrp-del rtoj-ovn_cluster_router -- lrp-add ovn_cluster_router rtoj-ovn_cluster_router 0a:58:64:40:00:01 100.64.0.1/16"}]}

there is no delete etcd key message

notification events:

> [{"type":"\u0000","kv":{"key":"ovsdb/nb/OVN_Northbound/Logical_Router/d2b112f2-     56b2-41bf-b9ce-4c1641b93bf4","create_revision":1,"mod_revision":2,"version":0,"value":"{\"_uuid\":[\"uuid\",\"d2b112f2-56b2-41bf-b9ce-4c1641b93bf4\"],\"_version\":[\"uuid\",\"006c9224-6b1b-413b-b6bf-a5972cd7d524\"],\"enabled\":[\"se     t\",[]],\"external_ids\":[\"map\",[[\"k8s-cluster-router\",\"yes\"]]],\"load_balancer\":[\"set\",[]],\"name\":\"ovn_cluster_router\",\"nat\":[\"set\",[]],\"options\":[\"map\",[]],\"policies\":[\"set\",[]],\"ports\":[\"set\",[[\"uuid     \",\"bb3a3320-75fb-4699-a916-ad757e1cc1d0\"],[\"uuid\",\"ac41801d-0e5e-4ec7-9657-e046e6c2253c\"]]],\"static_routes\":[\"set\",[]]}","lease":0},"prev_kv":{"key":"ovsdb/nb/OVN_Northbound/Logical_Router/d2b112f2-56b2-41bf-b9ce-4c1641b9     3bf4","create_revision":1,"mod_revision":1,"version":0,"value":"{\"_uuid\":[\"uuid\",\"d2b112f2-56b2-41bf-b9ce-4c1641b93bf4\"],\"_version\":[\"uuid\",\"395c8a77-ebc0-41dd-a474-e767d54a1660\"],\"enabled\":[\"set\",[]],\"external_ids\     ":[\"map\",[[\"k8s-cluster-router\",\"yes\"]]],\"load_balancer\":[\"set\",[]],\"name\":\"ovn_cluster_router\",\"nat\":[\"set\",[]],\"options\":[\"map\",[]],\"policies\":[\"set\",[]],\"ports\":[\"set\",[[\"uuid\",\"bb3a3320-75fb-4699     -a916-ad757e1cc1d0\"],[\"uuid\",\"0535086f-f347-4bee-a130-fb24034174e0\"]]],\"static_routes\":[\"set\",[]]}","lease":0}},{"type":"\u0000","kv":{"key":"ovsdb/nb/OVN_Northbound/Logical_Router_Port/ac41801d-0e5e-4ec7-9657-e046e6c2253c"     ,"create_revision":1,"mod_revision":1,"version":0,"value":"{\"_uuid\":[\"uuid\",\"ac41801d-0e5e-4ec7-9657-e046e6c2253c\"],\"_version\":[\"uuid\",\"aaef04a2-8d83-4280-a9f8-74a88597a68f\"],\"enabled\":[\"set\",[]],\"external_ids\":[\"     map\",[]],\"gateway_chassis\":[\"set\",[]],\"ha_chassis_group\":[\"set\",[]],\"ipv6_prefix\":[\"set\",[]],\"ipv6_ra_configs\":[\"map\",[]],\"mac\":\"0a:58:64:40:00:01\",\"name\":\"rtoj-ovn_cluster_router\",\"networks\":\"100.64.0.1/     16\",\"options\":[\"map\",[]],\"peer\":[\"set\",[]]}","lease":0},"prev_kv":null}]

Notification:

> {"Logical_Router":{"d2b112f2-56b2-41bf-b9ce-4c1641b93bf4":{"new":{"external     _ids":["map",[["k8s-cluster-router","yes"]]],"name":"ovn_cluster_router","options":["map",[]],"ports":["set",[["uuid","bb3a3320-75fb-4699-a916-ad757e1cc1d0"],["uuid","ac41801d-0e5e-4ec7-9657-e046e6c2253c"]]]},"old":{"_version":["uui     d","395c8a77-ebc0-41dd-a474-e767d54a1660"],"ports":["set",[["uuid","bb3a3320-75fb-4699-a916-ad757e1cc1d0"],["uuid","0535086f-f347-4bee-a130-fb24034174e0"]]]}}},"Logical_Router_Port":{"ac41801d-0e5e-4ec7-9657-e046e6c2253c":{"new":{"e     xternal_ids":["map",[]],"ipv6_ra_configs":["map",[]],"mac":"0a:58:64:40:00:01","name":"rtoj-ovn_cluster_router","networks":"100.64.0.1/16","options":["map",[]]}}}}
 710 I0624 03:21:21.428425      14 monitor.go:217]  "msg"="notify" "client"="172.18.0.2:53838" "hid"="Y6aLbEWCgbxuaLjERyrpZN" "jsonValue"=["monid","OVN_Northbound"] "revChecker.revision"=50 "revision"=51 "wg == nil"=true
 711 I0624 03:21:21.428454      14 monitor.go:180]  "msg"="send notification" "client"="172.18.0.2:53846" "hid"="XyXThwWL45qyjnwfEFykcR" "jsonValue"=["monid","OVN_Northbound"] "updates"={"Logical_Router":{"d2b112f2-56b2-41bf-b9ce-4c1641b     93bf4":{"modify":{"ports":["set",[["uuid","ac41801d-0e5e-4ec7-9657-e046e6c2253c"],["uuid","0535086f-f347-4bee-a130-fb24034174e0"]]]}}},"Logical_Router_Port":{"ac41801d-0e5e-4ec7-9657-e046e6c2253c":{"insert":{"external_ids":["map",[]     ],"ipv6_ra_configs":["map",[]],"mac":"0a:58:64:40:00:01","name":"rtoj-ovn_cluster_router","networks":"100.64.0.1/16","options":["map",[]]}}}}
 
Transaction response 

> "response"={"result":[{"count":1},{"uuid":["uuid","ac41801d-0e5e-4ec7-9657-e046e6c2253c"]},     {}]}

**Comment by hunchback** [comment]
```
{
"op":"mutate",
"table":"Logical_Router", 
"mutations":[["ports","delete",["set",[["uuid","0535086f-f347-4bee-a130-fb24034174e0"]]]],["ports","insert",["set",[["named-uuid","row6dc0b1cf_7554_4a41_a57e_2f6d51852632"]]]]],
"where":[["_uuid","==",["uuid","d2b112f2-56b2-41bf-b9ce -4c1641b93bf4"]]]
}
```

**Comment by roytman** [comment]
The situation is more complicated. We have to remove week references .... Let's discuss

**Comment by roytman** [comment]
test case was submitetd in #269 .
in the latest oVNk logs I don't see mutate operations.

**Comment by roytman** [comment]
We removed notification creation by transactions, so the issue is not relevant now.
